print("What is your name?")
name = input()
print("How old are you?")
age = input()
print("Where are you live?")
home = input()
print(f"This is {name}")
print(f"It is {age}")
print(f"(S)he live in {home}")